In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
returns = pd.read_csv("returns.csv")

In [5]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Returns:", returns.shape)

Customers: (3000, 12)
Products: (345, 10)
Orders: (14000, 20)
Order Items: (29671, 11)
Returns: (2433, 15)

In [6]:
print("CUSTOMERS")
print(customers.columns.tolist())

print("\nPRODUCTS")
print(products.columns.tolist())

print("\nORDERS")
print(orders.columns.tolist())

print("\nORDER ITEMS")
print(order_items.columns.tolist())

print("\nRETURNS")
print(returns.columns.tolist())

CUSTOMERS
['customer_id', 'customer_name', 'country', 'region', 'currency_code', 'signup_date', 'acquisition_channel', 'preferred_device', 'newsletter_opt_in', 'first_order_date', 'lifetime_orders', 'lifetime_spend_usd']

PRODUCTS
['product_id', 'product_name', 'category', 'subcategory', 'brand', 'list_price_usd', 'unit_cost_usd', 'weight_kg', 'launch_date', 'is_active']

ORDERS
['order_id', 'customer_id', 'order_date', 'order_month', 'sales_channel', 'device_type', 'payment_method', 'shipping_country', 'shipping_region', 'currency_code', 'fx_rate_to_usd', 'items_count', 'gross_amount_local', 'discount_local', 'shipping_fee_local', 'tax_local', 'order_total_local', 'order_total_usd', 'order_status', 'delivery_days']

ORDER ITEMS
['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price_local', 'line_discount_local', 'line_total_local', 'line_total_usd', 'unit_cost_usd', 'line_profit_usd', 'currency_code']

RETURNS
['return_id', 'order_id', 'order_item_id', 'product_id', 'customer_id', 'return_date', 'return_month', 'days_to_return', 'quantity_returned', 'return_reason', 'item_condition', 'refund_amount_local', 'refund_amount_usd', 'restocked', 'currency_code']

In [7]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3000 non-null   object
 1   customer_name        3000 non-null   object
 2   country              3000 non-null   object
 3   region               3000 non-null   object
 4   currency_code        3000 non-null   object
 5   signup_date          3000 non-null   object
 6   acquisition_channel  3000 non-null   object
 7   preferred_device     3000 non-null   object
 8   newsletter_opt_in    3000 non-null   object
 9   first_order_date     2966 non-null   object
 10  lifetime_orders      3000 non-null   int64
 11  lifetime_spend_usd   3000 non-null   float64
dtypes: float64(1), int64(1), object(10)
memory usage: 281.4+ KB

In [8]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      345 non-null    object
 1   product_name    345 non-null    object
 2   category        345 non-null    object
 3   subcategory     345 non-null    object
 4   brand           345 non-null    object
 5   list_price_usd  345 non-null    float64
 6   unit_cost_usd   345 non-null    float64
 7   weight_kg       345 non-null    float64
 8   launch_date     345 non-null    object
 9   is_active       345 non-null    object
dtypes: float64(3), object(7)
memory usage: 27.1+ KB

In [9]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14000 entries, 0 to 13999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            14000 non-null  object
 1   customer_id         14000 non-null  object
 2   order_date          14000 non-null  object
 3   order_month         14000 non-null  object
 4   sales_channel       14000 non-null  object
 5   device_type         14000 non-null  object
 6   payment_method      14000 non-null  object
 7   shipping_country    14000 non-null  object
 8   shipping_region     14000 non-null  object
 9   currency_code       14000 non-null  object
 10  fx_rate_to_usd      14000 non-null  float64
 11  items_count         14000 non-null  int64
 12  gross_amount_local  14000 non-null  float64
 13  discount_local      14000 non-null  float64
 14  shipping_fee_local  14000 non-null  float64
 15  tax_local           14000 non-null  float64
 16  order_total_local   14000 non-null  float64
 17  order_total_usd     14000 non-null  float64
 18  order_status        14000 non-null  object
 19  delivery_days       12754 non-null  float64
dtypes: float64(8), int64(1), object(11)
memory usage: 2.1+ MB

In [10]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29671 entries, 0 to 29670
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_item_id        29671 non-null  object
 1   order_id             29671 non-null  object
 2   product_id           29671 non-null  object
 3   quantity             29671 non-null  int64
 4   unit_price_local     29671 non-null  float64
 5   line_discount_local  29671 non-null  float64
 6   line_total_local     29671 non-null  float64
 7   line_total_usd       29671 non-null  float64
 8   unit_cost_usd        29671 non-null  float64
 9   line_profit_usd      29671 non-null  float64
 10  currency_code        29671 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 2.5+ MB

In [11]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2433 entries, 0 to 2432
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   return_id            2433 non-null   object
 1   order_id             2433 non-null   object
 2   order_item_id        2433 non-null   object
 3   product_id           2433 non-null   object
 4   customer_id          2433 non-null   object
 5   return_date          2433 non-null   object
 6   return_month         2433 non-null   object
 7   days_to_return       2433 non-null   int64
 8   quantity_returned    2433 non-null   int64
 9   return_reason        2433 non-null   object
 10  item_condition       2433 non-null   object
 11  refund_amount_local  2433 non-null   float64
 12  refund_amount_usd    2433 non-null   float64
 13  restocked            2433 non-null   object
 14  currency_code        2433 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 285.2+ KB

In [13]:
customers.head()

,customer_id,customer_name,country,region,currency_code,signup_date,acquisition_channel,preferred_device,newsletter_opt_in,first_order_date,lifetime_orders,lifetime_spend_usd
0,CST-00001,Kofi Garcia,Saudi Arabia,Middle East,SAR,08-11-2023,Organic Search,Desktop,Yes,01-07-2024,7,3584.40
1,CST-00002,Diego Okafor,Germany,Europe,EUR,17-11-2023,Direct,Mobile,No,23-06-2024,4,1867.09
2,CST-00003,Ahmed Garcia,Germany,Europe,EUR,15-08-2023,Organic Search,Desktop,No,19-05-2024,3,1762.15
3,CST-00004,Grace Costa,United States,North America,USD,07-01-2025,Paid Search,Desktop,Yes,14-03-2026,2,669.49
4,CST-00005,Alex Patel,Japan,Asia-Pacific,JPY,12-06-2023,Organic Search,Mobile,Yes,29-01-2024,5,1136.69

In [14]:
products.head()

,product_id,product_name,category,subcategory,brand,list_price_usd,unit_cost_usd,weight_kg,launch_date,is_active
0,PRD-0001,Northline Footwear 0001,Apparel,Footwear,Northline,105.82,51.08,4.97,26-06-2023,Yes
1,PRD-0002,Solstice T-Shirt 0002,Apparel,T-Shirts,Marlowe,90.07,42.16,3.56,15-11-2023,Yes
2,PRD-0003,Ferrix Footwear 0003,Apparel,Footwear,Brightfold,127.19,56.37,0.44,04-11-2022,Yes
3,PRD-0004,Vantia Dresse 0004,Apparel,Dresses,Kestrel,82.41,34.30,5.59,30-11-2023,Yes
4,PRD-0005,Brightfold Footwear 0005,Apparel,Footwear,Northline,28.14,13.37,4.37,01-01-2022,Yes

In [15]:
orders.head()

,order_id,customer_id,order_date,order_month,sales_channel,device_type,payment_method,shipping_country,shipping_region,currency_code,fx_rate_to_usd,items_count,gross_amount_local,discount_local,shipping_fee_local,tax_local,order_total_local,order_total_usd,order_status,delivery_days
0,ORD-008373,CST-01476,01-01-2024,2024-01,Mobile App,Mobile,Credit Card,United Arab Emirates,Middle East,AED,3.67,2,954.35,0.00,0.0,47.72,1002.07,273.04,Shipped,1.0
1,ORD-013085,CST-00125,01-01-2024,2024-01,Mobile App,Mobile,Cash on Delivery,India,Asia-Pacific,INR,83.20,4,38571.52,1722.73,0.0,6632.78,43481.57,522.62,Delivered,9.0
2,ORD-013781,CST-02849,01-01-2024,2024-01,Web Store,Desktop,Cash on Delivery,Australia,Asia-Pacific,AUD,1.52,7,2752.98,197.66,0.0,255.53,2810.85,1849.24,Delivered,5.0
3,ORD-007897,CST-00624,01-01-2024,2024-01,Web Store,Desktop,Credit Card,India,Asia-Pacific,INR,83.20,7,101415.79,5440.98,0.0,17275.47,113250.28,1361.18,Delivered,8.0
4,ORD-008525,CST-02656,01-01-2024,2024-01,Web Store,Desktop,Cash on Delivery,United Kingdom,Europe,GBP,0.79,8,814.22,43.43,0.0,154.16,924.95,1170.82,Delivered,7.0

In [16]:
order_items.head()

,order_item_id,order_id,product_id,quantity,unit_price_local,line_discount_local,line_total_local,line_total_usd,unit_cost_usd,line_profit_usd,currency_code
0,ITM-000001,ORD-000001,PRD-0061,1,42.78,0.00,42.78,42.78,18.99,23.79,USD
1,ITM-000002,ORD-000001,PRD-0311,1,96.79,0.00,96.79,96.79,53.60,43.19,USD
2,ITM-000003,ORD-000002,PRD-0335,1,282.11,0.00,282.11,75.23,39.08,36.15,SAR
3,ITM-000004,ORD-000003,PRD-0092,2,1122.95,369.42,1876.48,1379.76,632.31,115.14,CAD
4,ITM-000005,ORD-000003,PRD-0301,1,96.07,31.15,64.92,47.74,35.15,12.59,CAD

In [17]:
returns.head()

,return_id,order_id,order_item_id,product_id,customer_id,return_date,return_month,days_to_return,quantity_returned,return_reason,item_condition,refund_amount_local,refund_amount_usd,restocked,currency_code
0,RET-000001,ORD-003001,ITM-006348,PRD-0016,CST-00837,30-01-2024,2024-01,28,1,Changed mind,Damaged,12720.96,152.90,No,INR
1,RET-000002,ORD-013740,ITM-029103,PRD-0049,CST-01069,11-01-2024,2024-01,9,1,Not as described,Damaged,592.48,161.44,Yes,AED
2,RET-000003,ORD-013740,ITM-029104,PRD-0158,CST-01069,10-01-2024,2024-01,8,1,Changed mind,Damaged,122.89,33.49,Yes,AED
3,RET-000004,ORD-005198,ITM-010985,PRD-0011,CST-00443,17-01-2024,2024-01,13,1,Wrong size or fit,Damaged,13157.86,158.15,Yes,INR
4,RET-000005,ORD-009829,ITM-020765,PRD-0208,CST-00528,31-01-2024,2024-01,24,1,Changed mind,Resellable,228.00,228.00,No,USD

In [18]:
tables = {
    "customers": customers,
    "products": products,
    "orders": orders,
    "order_items": order_items,
    "returns": returns
}

for name, df in tables.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"{'='*50}")
    print("Shape:", df.shape)
    print("\nMissing values:")
    print(df.isnull().sum())
    print("\nDuplicate rows:", df.duplicated().sum())

==================================================
CUSTOMERS
==================================================
Shape: (3000, 12)

Missing values:
customer_id             0
customer_name           0
country                 0
region                  0
currency_code           0
signup_date             0
acquisition_channel     0
preferred_device        0
newsletter_opt_in       0
first_order_date       34
lifetime_orders         0
lifetime_spend_usd      0
dtype: int64

Duplicate rows: 0

==================================================
PRODUCTS
==================================================
Shape: (345, 10)

Missing values:
product_id        0
product_name      0
category          0
subcategory       0
brand             0
list_price_usd    0
unit_cost_usd     0
weight_kg         0
launch_date       0
is_active         0
dtype: int64

Duplicate rows: 0

==================================================
ORDERS
==================================================
Shape: (14000, 20)

Missing values:
order_id                 0
customer_id              0
order_date               0
order_month              0
sales_channel            0
device_type              0
payment_method           0
shipping_country         0
shipping_region          0
currency_code            0
fx_rate_to_usd           0
items_count              0
gross_amount_local       0
discount_local           0
shipping_fee_local       0
tax_local                0
order_total_local        0
order_total_usd          0
order_status             0
delivery_days         1246
dtype: int64

Duplicate rows: 0

==================================================
ORDER_ITEMS
==================================================
Shape: (29671, 11)

Missing values:
order_item_id          0
order_id               0
product_id             0
quantity               0
unit_price_local       0
line_discount_local    0
line_total_local       0
line_total_usd         0
unit_cost_usd          0
line_profit_usd        0
currency_code          0
dtype: int64

Duplicate rows: 0

==================================================
RETURNS
==================================================
Shape: (2433, 15)

Missing values:
return_id              0
order_id               0
order_item_id          0
product_id             0
customer_id            0
return_date            0
return_month           0
days_to_return         0
quantity_returned      0
return_reason          0
item_condition         0
refund_amount_local    0
refund_amount_usd      0
restocked              0
currency_code          0
dtype: int64

Duplicate rows: 0

In [19]:
for name, df in tables.items():
    print("\n" + "="*50)
    print(name.upper())
    print("="*50)

    print("Shape:", df.shape)

    print("\nMissing values:")
    print(df.isnull().sum())

    print("\nDuplicate rows:", df.duplicated().sum())

==================================================
CUSTOMERS
==================================================
Shape: (3000, 12)

Missing values:
customer_id             0
customer_name           0
country                 0
region                  0
currency_code           0
signup_date             0
acquisition_channel     0
preferred_device        0
newsletter_opt_in       0
first_order_date       34
lifetime_orders         0
lifetime_spend_usd      0
dtype: int64

Duplicate rows: 0

==================================================
PRODUCTS
==================================================
Shape: (345, 10)

Missing values:
product_id        0
product_name      0
category          0
subcategory       0
brand             0
list_price_usd    0
unit_cost_usd     0
weight_kg         0
launch_date       0
is_active         0
dtype: int64

Duplicate rows: 0

==================================================
ORDERS
==================================================
Shape: (14000, 20)

Missing values:
order_id                 0
customer_id              0
order_date               0
order_month              0
sales_channel            0
device_type              0
payment_method           0
shipping_country         0
shipping_region          0
currency_code            0
fx_rate_to_usd           0
items_count              0
gross_amount_local       0
discount_local           0
shipping_fee_local       0
tax_local                0
order_total_local        0
order_total_usd          0
order_status             0
delivery_days         1246
dtype: int64

Duplicate rows: 0

==================================================
ORDER_ITEMS
==================================================
Shape: (29671, 11)

Missing values:
order_item_id          0
order_id               0
product_id             0
quantity               0
unit_price_local       0
line_discount_local    0
line_total_local       0
line_total_usd         0
unit_cost_usd          0
line_profit_usd        0
currency_code          0
dtype: int64

Duplicate rows: 0

==================================================
RETURNS
==================================================
Shape: (2433, 15)

Missing values:
return_id              0
order_id               0
order_item_id          0
product_id             0
customer_id            0
return_date            0
return_month           0
days_to_return         0
quantity_returned      0
return_reason          0
item_condition         0
refund_amount_local    0
refund_amount_usd      0
restocked              0
currency_code          0
dtype: int64

Duplicate rows: 0

In [20]:
for name, df in tables.items():
    print(f"{name}:")
    print("Shape:", df.shape)
    print("Missing:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())
    print()

customers:
Shape: (3000, 12)
Missing: 34
Duplicate rows: 0

products:
Shape: (345, 10)
Missing: 0
Duplicate rows: 0

orders:
Shape: (14000, 20)
Missing: 1246
Duplicate rows: 0

order_items:
Shape: (29671, 11)
Missing: 0
Duplicate rows: 0

returns:
Shape: (2433, 15)
Missing: 0
Duplicate rows: 0

In [21]:
orders.isnull().sum()

order_id                 0
customer_id              0
order_date               0
order_month              0
sales_channel            0
device_type              0
payment_method           0
shipping_country         0
shipping_region          0
currency_code            0
fx_rate_to_usd           0
items_count              0
gross_amount_local       0
discount_local           0
shipping_fee_local       0
tax_local                0
order_total_local        0
order_total_usd          0
order_status             0
delivery_days         1246
dtype: int64

In [22]:
orders.loc[
    orders["delivery_days"].isna(),
    "order_status"
].value_counts()

order_status
Cancelled     807
Processing    439
Name: count, dtype: int64

In [23]:
missing_first_order = customers[
    customers["first_order_date"].isna()
]

print("Customers with missing first_order_date:",
      len(missing_first_order))

print("Those customers who have orders:",
      missing_first_order["customer_id"].isin(
          orders["customer_id"]
      ).sum())

Customers with missing first_order_date: 34
Those customers who have orders: 6

In [24]:
missing_with_orders = missing_first_order[
    missing_first_order["customer_id"].isin(
        orders["customer_id"]
    )
]

print(
    missing_with_orders[
        ["customer_id", "customer_name", "signup_date",
         "first_order_date", "lifetime_orders",
         "lifetime_spend_usd"]
    ]
)

     customer_id   customer_name signup_date first_order_date  \
192    CST-00193     Nina Garcia  09-05-2025              NaN
644    CST-00645     Priya Patel  09-12-2025              NaN
980    CST-00981     Ivan Dubois  04-03-2024              NaN
1152   CST-01153  Jonas Nakamura  18-05-2023              NaN
1853   CST-01854    Diego Haddad  09-05-2025              NaN
2928   CST-02929  Grace Andersen  08-08-2023              NaN

      lifetime_orders  lifetime_spend_usd
192                 0                 0.0
644                 0                 0.0
980                 0                 0.0
1152                0                 0.0
1853                0                 0.0
2928                0                 0.0

In [25]:
actual_first_orders = (
    orders[
        orders["customer_id"].isin(
            missing_with_orders["customer_id"]
        )
    ]
    .groupby("customer_id")["order_date"]
    .min()
)

print(actual_first_orders)

customer_id
CST-00193    04-03-2026
CST-00645    19-02-2026
CST-00981    26-10-2025
CST-01153    27-02-2026
CST-01854    20-05-2026
CST-02929    18-01-2024
Name: order_date, dtype: object

In [26]:
problem_orders = orders[
    orders["customer_id"].isin(problem_customer_ids)
]

print(
    problem_orders[
        ["customer_id", "order_id", "order_date",
         "order_status", "order_total_usd"]
    ].sort_values(["customer_id", "order_date"])
)

NameError: name 'problem_customer_ids' is not defined

In [27]:
# Customers whose first_order_date is missing
missing_first_order = customers[
    customers["first_order_date"].isna()
]

# Among them, find the customer IDs who actually have orders
problem_customer_ids = missing_first_order[
    missing_first_order["customer_id"].isin(
        orders["customer_id"]
    )
]["customer_id"]

# Check those customers' orders
problem_orders = orders[
    orders["customer_id"].isin(problem_customer_ids)
]

print(
    problem_orders[
        ["customer_id", "order_id", "order_date",
         "order_status", "order_total_usd"]
    ].sort_values(["customer_id", "order_date"])
)

      customer_id    order_id  order_date order_status  order_total_usd
10947   CST-00193  ORD-001809  04-03-2026    Cancelled          1916.04
10642   CST-00645  ORD-012594  19-02-2026    Cancelled           394.01
13079   CST-00645  ORD-002357  26-05-2026    Cancelled            83.68
7994    CST-00981  ORD-007387  26-10-2025    Cancelled           748.46
10847   CST-01153  ORD-013992  27-02-2026    Cancelled           807.16
12935   CST-01854  ORD-004472  20-05-2026    Cancelled            80.23
72      CST-02929  ORD-005742  18-01-2024    Cancelled           116.09

In [28]:
# Orders → Customers
missing_customers = orders[
    ~orders["customer_id"].isin(customers["customer_id"])
]

# Order Items → Orders
missing_orders = order_items[
    ~order_items["order_id"].isin(orders["order_id"])
]

# Order Items → Products
missing_products = order_items[
    ~order_items["product_id"].isin(products["product_id"])
]

# Returns → Order Items
missing_return_items = returns[
    ~returns["order_item_id"].isin(order_items["order_item_id"])
]

print("Orders with missing customer:", len(missing_customers))
print("Order items with missing order:", len(missing_orders))
print("Order items with missing product:", len(missing_products))
print("Returns with missing order item:", len(missing_return_items))

Orders with missing customer: 0
Order items with missing order: 0
Order items with missing product: 0
Returns with missing order item: 0

In [29]:
calculated_line_total = (
    order_items["quantity"] * order_items["unit_price_local"]
    - order_items["line_discount_local"]
)

difference = (
    calculated_line_total
    - order_items["line_total_local"]
).abs()

print("Maximum difference:", difference.max())
print("Rows with mismatch:", (difference > 0.01).sum())

Maximum difference: 5.820766091346741e-11
Rows with mismatch: 0

In [30]:
x = order_items.groupby("order_id").apply(
    lambda x: (x["line_total_local"] + x["line_discount_local"]).sum()
)

print(x.head())

order_id
ORD-000001     139.57
ORD-000002     282.11
ORD-000003    5059.90
ORD-000004     223.92
ORD-000005    3603.02
dtype: float64

/var/folders/td/q8vkq5595rz8hq4mzlhg10l80000gp/T/ipykernel_92145/3207063686.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  x = order_items.groupby("order_id").apply(